name: Add label on merge conflict
on:
  pull_request_target:
    branches: [ main ]
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label Conflicting Pull Requests
        uses: eps1lon/actions-label-merge-conflict@v2.0.0
        with: 
          dirtyLabel: "Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, which you need to resolve! :partying_face: Don't need to worry at all, please follow the steps here - https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts"
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
